### ISSUE TITLE
Why is there no documentation?

### ISSUE THREAD

**Issue by jackadam1981** [glpi-project/docker-images#97]
Why is there no documentation?

docker run  -p 8086:80 ghcr.io/glpi-project/glpi-nightly:main

Web server root directory configuration is incorrect, it should be "/var/www/glpi/public". See installation documentation for more details.

need to be updated?

**Comment by cedric-anne** [comment]
Hi,

There is no documentation because images built from current repository are not yet ready to be used outside a development environment, and, as people that are using them did not yet asked for any documentation, we did not take time to do it.

Anyway, the Apache configuration should indeed be updated to fix the nightly image of the GLPI 10.1 version.
